end_effector_controller:
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - iiwa_joint_7

body_controller:
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100

# gazebo_ros_control:
#   pid_gains:
#       Joint_5:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Joint_6:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Joint_4:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Joint_1:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Joint_2:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Joint_3:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Finger_1:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
#       Finger_2:
#         p: 100
#         d: 1
#         i: 1
#         i_clamp: 1
