controller_list:
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - Finger_1
      - Finger_2
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
initial:  # Define initial robot poses per group
  - group: end_effector
    pose: full_open
  - group: body
    pose: home